### PR TITLE
Fixed pagination issue in treegrid

### PR DESCRIPTION
**Pull request by avnish1306**
When the grid type is tree grid and pagination is true then th "rowNum" which is number of rows in a page is getting changed to 10000 because there is a mistake in setTreeGrid function as if($t.p.rowTotal === null ) { $t.p.rowNum = 10000; }
$t.p.rowNum =10000 should be $t.p.rowTotal = 10000;

### CODE REVIEW

**Comment by avnish1306** [comment]
treeGridIssue

**Comment by tonytomov** [comment]
Can you please provide a exmaple which demostartes this problem (Please provide a real demo example with data). 

Moreover I see you use a old version of jqGrid as seen into the pickture

**Comment by avnish1306** [comment]
Since my ongoing project is not on web so i created a demo which will be sufficient to show the issue.
 
rowNum is set to **2**, so the grid should show **2 record/page** as it is expected behavior but it's showing all the records. But after my fix that i proposed the page is showing the expected behavior.
You can navigate to [this](https://codepen.io/avnishawi/pen/LYEoYRL) to see yourself https://codepen.io/avnishawi/pen/LYEoYRL.
I'm also attaching the screenshots which will show **before correction** , **after correction** output and also the **debugger**.
beforeCorrection1
afterCorrection
debugging

**Comment by tonytomov** [comment]
The version you use does not support paging (as per problem reported) and  rowNum parameter does not have sense in treeGrid that is the reason to be set a relative big number - this is the behaviour prior to version 5.3. As of version 5.3 we support paging under certain conditions. Please see this documentation - http://www.guriddo.net/documentation/guriddo/javascript/user-guide/treegrid/#paging

**Pull request closed without merging**
