### PR TITLE
Hide no records row when emptyRecordRow is false

### PR DESCRIPTION
**Pull request by fredsal**

### CODE REVIEW

**Comment by tonytomov** [comment]
Hello,

Firs of all thank you for the participation.

I'm not sure that I will accept this pull request. The reason for this is simple.

The origin to have **no record row** was caused by the fact that if there is no data and we have 
a relative many columns in  grid which horizontal scroll -  the horizontal scrollbar in this case disappear.
Imagine that here you have toolbar search, then the data in search field (suppose the last field in  the column) is hidden and the user can not access their search field to change it.

**Comment by fredsal** [comment]
@tonytomov , maybe when emptyRecordRow is false, set style css visibility to hidden? I change the pull request for another review
thanks for your time, great grid by the way

**Comment by PaolaRuby** [comment]
@tonytomov it's posible set `visibility:hidden` when `emptyRecordRow===false`?
It's maybe help to everyone wich don´t wanna see that row
image

**Comment by tonytomov** [comment]
@PaolaRuby ,

When this parameter is false the row is not displayed.

**Pull request merged**
